### ISSUE TITLE
Catch up with bootstrap v4.alpha3

### ISSUE THREAD

**Issue by li3p** [kzima/vuestrap#8]
Bootstrap V4.alpha3 just released yesterday, any plan to catch up with this version?
There are some significant changes since V4.alpha2, some of the changes are breaking changes.

**Comment by kzima** [comment]
@li3p thanks for the heads up about the B4. I am not planning to do any more work on vuestrap unfortunately.  As much as I like vue js, I switched to react js and I am no longer planning to support vuerstap project. 

Is this something you would like to contribute to?

**Comment by li3p** [comment]
Hi, @kzima ,  I think I will stick with vuejs and vuestrap for some projects for a period. And also I like using vuestrap can let me get rid of Juqery.  so I would like continue your works on vuestrap if you really have no plan to support it since now.

**Comment by li3p** [comment]
Hi, @kzima . I have committed changes on bootstrap.v4.alpha3 both in `vuestrap` and `vuestrap-base-components` repos. Can you help me review it ? Would it be better if I commit such changes by a PR next time? and do we need publish those changes to NPM or some other public repositories?

**Comment by kzima** [comment]
Hi @li3p, if you are confident that your update is good enough, just merge it yourself. PR could be good solution however, I could always have a look before it is merged. There might be few things that could get broken, so I would update vuestrap dependency on vuestrap-base-components and check if everything works ok. Usually there would be some `less` errors on webpack compilation especially if some variable name is missing or changed.

**Comment by li3p** [comment]
Hi @kzima , next time I will use PR to commit changes. Any update on the new commit ? Let me know if there something I can do.
